### ISSUE TITLE
pipeline crash after updating to latest pangolin version v4

### ISSUE THREAD

**Issue by kittychaseNC** [UPHL-BioNGS/Cecret#94] opened 2022-04-04 16:02 UTC
error: ValueError: Usecols do not match columns, columns expected but not found: ['pango_version', 'pangoLEARN_version', 'status']

column headings have changed/been modified

**Comment by lbiernot** [comment] 2022-04-07 13:50
Possible solution https://github.com/lbiernot/Cecret/pull/1/commits/c52ce639bf54aa32fc7e6168137e35c4c1067d9b

**Comment by lbiernot** [comment] 2022-04-07 19:24
This https://github.com/lbiernot/Cecret/pull/1/commits/ce012d9970af5bf5a0b9638ad955b2dd1ed51a72 is also needed to actually use pangolin 3.1.20

**Comment by erinyoung** [comment] 2022-04-07 20:45
I have a fix that's almost ready for production: https://github.com/UPHL-BioNGS/Cecret/pull/95

I am running it through tests for Pangolin 4.0.3, and I should have this merged into master by the end of today.

In the meantime, these edits are available with 
```
nextflow run UPHL-BioNGS/Cecret -profile singularity -r edits
```

**Comment by lbiernot** [comment] 2022-04-07 22:46
@erinyoung great to hear. And by the way, good job - your Cecret worflow is really good. However I strongly suggest pinning docker image versions to avoid this kind of issues in the future.

**Comment by erinyoung** [comment] 2022-04-08 00:09
docker containers can be defined in a config file and are already "pinnable". 

A template for a config file that you could copy and edit is found in [Cecret/configs/cecret_config_template.config](https://github.com/UPHL-BioNGS/Cecret/blob/master/configs/cecret_config_template.config)

You would want to edit a line like the following:

```
  withName:pangolin{
    container = staphb/pangolin:whatever
  }
```

Although, I'm not sure how useful an old pangolin container is.

**Closed** 2022-04-08 00:09 UTC

**Comment by lbiernot** [comment] 2022-04-08 01:07
@erinyoung the fact that a new pangolin docker image was published 7 days ago doesn't render the former version immediately useless. It's considered a good practice in software development to pin the dependency versions.
Using ":latest" tag means that the way your workflow works can change anytime without your awareness.
Please don't consider my suggestions as something bad. I honestly appreciate your work and I'm simply trying to help.

**Comment by erinyoung** [comment] 2022-04-08 14:50
Thank you for your suggestions. Pangolin has had three updates and is now on 4.0.3. If you would like to pin a specific container for your pipeline, I recommend editing your config file.

**Comment by lbiernot** [comment] 2022-04-15 09:45
@erinyoung hello again. Thank you, I know how to pin versions and in fact I'm pinning them all now.
Consider this
```
docker image ls | grep staphb/samtools
staphb/samtools                                                         latest                         442301e8069e   18 months ago   373MB
```
Nextflow doesn't pull docker images. If the image tag defined in your workflow is already present, docker will simply use it. So in this example I have an old samtools image and your workflow was still using it until now. I know your intention was to use the latest available image by default but it's not how it works.
So coming back to pangolin, if I have pulled staphb/pangolin:latest 2 years ago, your workflow would use pangolin version 1.1.14 on my machine beceause it was tagged "latest" when I pulled it.
As long as all your dependencies are only using tag "latest" your workflow will use the most recent dependencies only if the host machine doesn't have any dependency images pulled already. Otherwise it will use even very old versions without any warning. And this is exactly what happened yesterday on one of my target machines. The workflow failed on samtools_ampliconstats process because an 18 months old samtools image tagged "latest" was present on the host.

You want be able to reproduce any of similar issues reported by other users because on every machine there can be any combination of incompatible dependencies.

**Comment by erinyoung** [comment] 2022-04-15 17:46
Thank you for your feedback!

If you set the singularity download folder, you'll run into the same issue with singularity. This is a nextflow "feature". 

If you want to make sure you're always using the latest container, you can set nextflow to always pull the docker container in your config file.

If you wanted to add it to the docker scope, it would look something like this

```
docker {
    runOptions = '--pull=always'
}
```

Or if you just wanted to update it without the scope, it'd look like this

```
docker.runOptions = '--pull=always'
```
